sudo: true

language: python
python:
- 2.7
- 3.3
- 3.4
- 3.5

cache:
  pip: true
  directories:
  - env

env:
  global:
  - RANDOM_SEED=12345
  # TODO: change this token: http://benlimmer.com/2013/12/26/automatically-publish-javadoc-to-gh-pages-with-travis-ci/
  - secure: "C47GeEhpKhKZ/VUH6zXX+drGw9HdZt05thVikBUhXY8UbdbujVsjG5z8w7/GMpCmHIVKrijxQ5ZCF3HSSk/VBHMHPIR9AtYg3gOjuBmzNuhinYgC6JH7fZdDlDUKOU2U92h8gl0j/6CYIkLhPF211bpc6mSeOfSEIdz3YMcpvvc="

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scikit-learn pip wheel
  - source activate test-environment
  - pip install coveralls scrutinizer-ocular flask flask_restful flask_redis
  - python setup.py install

before_script:
- make env
- make depends-ci

script:
- make ci

after_success:
- coveralls
- ocular

after_script: >
  echo $TRAVIS_BRANCH; echo $TRAVIS_PULL_REQUEST;
  if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
    # Generate site
    make mkdocs ;
    # Configure Git with Travis CI information
    git config --global user.email "travis@travis-ci.org" ;
    git config --global user.name "travis-ci" ;
    # Delete the current repository
    rm -rf .git ;
    # Rebuild the repository from the generated files and push to GitHub pages
    cd site ;
    git init ;
    git add . ;
    git commit -m "Deploy Travis CI build $TRAVIS_BUILD_NUMBER to GitHub pages" ;
    git push -f https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG} master:gh-pages ;
  fi

notifications:
  email:
    on_success: never
    on_failure: change
