name: cf-predict
dependencies:
- flask=0.10.1=py35_1
- gunicorn=19.1.0=py35_0
- itsdangerous=0.24=py35_0
- jedi=0.9.0=py35_0
- jinja2=2.8=py35_0
- markupsafe=0.23=py35_0
- mkl=11.3.1=0
- numpy=1.10.4=py35_0
- openssl=1.0.2g=0
- pastedeploy=1.5.2=py35_1
- pep8=1.7.0=py35_0
- pip=8.0.3=py35_0
- py=1.4.31=py35_0
- pytest=2.8.5=py35_0
- python=3.5.1=0
- readline=6.2=2
- rope=0.9.4=py35_1
- scikit-learn=0.17.1=np110py35_0
- scipy=0.17.0=np110py35_0
- setuptools=20.1.1=py35_0
- sqlalchemy=1.0.12=py35_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- werkzeug=0.11.4=py35_0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zlib=1.2.8=0
- pip:
  - aniso8601==1.1.0
  - astroid==1.4.4
  - autopep8==1.2.2
  - binaryornot==0.4.0
  - bleach==1.4.2
  - cf-predict (/Users/ronert/Dropbox/Projects/cf-predict)==0.0.0
  - chardet==2.3.0
  - click==6.3
  - colorama==0.3.6
  - cookiecutter==1.3.0
  - coverage==4.0.3
  - docformatter==0.7.1
  - docutils==0.12
  - flake8==2.5.4
  - flask-redis==0.1.0
  - flask-restful==0.3.5
  - future==0.15.2
  - html5lib==0.9999999
  - httpie==0.9.3
  - importmagic==0.1.3
  - lazy-object-proxy==1.2.1
  - livereload==2.4.1
  - mako==1.0.3
  - markdown==2.4.1
  - mccabe==0.4.0
  - mkdocs==0.15.3
  - mkdocs-bootstrap==0.1.1
  - mkdocs-bootswatch==0.3.1
  - nose==1.3.7
  - pdoc==0.3.1
  - pep257==0.7.0
  - pep8radius==0.9.2
  - pyflakes==1.0.0
  - pygments==2.1.1
  - pylint==1.5.4
  - pytest-cov==2.2.1
  - pytest-describe==0.10.3
  - pytest-expecter==0.2.2.post3
  - pytest-flask==0.10.0
  - pytest-random==0.2
  - pytest-runfailed==0.5
  - python-dateutil==2.5.0
  - python-termstyle==0.1.10
  - pytz==2015.7
  - pyyaml==3.11
  - readme==0.7.1
  - readme-renderer==0.7.0
  - redis==2.10.5
  - requests==2.9.1
  - rope-py3k==0.9.4.post1
  - ruamel.base==1.0.0
  - ruamel.yaml==0.11.3
  - six==1.10.0
  - sniffer==0.3.5
  - testpackage==2.26
  - tornado==4.3
  - untokenize==0.1.1
  - whichcraft==0.1.1
  - wrapt==1.10.6
  - yapf==0.6.2

