name: cf-predict
dependencies:
- flask=0.10.1=py35_1
- gunicorn=19.1.0=py35_0
- numpy=1.10.4=py35_0
- pip=8.0.3=py35_0
- python=3.5.1=0
- scikit-learn=0.17.1=np110py35_0
- setuptools=20.1.1=py35_0
- wheel=0.29.0=py35_0
- pip:
  - Flask-Redis==0.1.0
  - Flask-RESTful==0.3.5
  - mockredispy==2.9.3
  - pytest==2.9.1
  - pytest-capturelog==0.7
  - pytest-cov==2.2.1
  - pytest-describe==0.10.3
  - pytest-expecter==0.2.2.post3
  - pytest-flask==0.10.0
  - pytest-random==0.2
  - pytest-runfailed==0.5
